spring.application.name=websocket-service
server.port=8084

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Queue and Exchange for Hourly Energy Consumption
rabbitmq.exchange.energy=energy.hourly.exchange
rabbitmq.queue.energy=energy.hourly.queue
rabbitmq.routing.key.energy=energy.hourly.key

# Overconsumption alerts
rabbitmq.queue.alert=energy.alert.queue
rabbitmq.routing.key.alert=alert.overconsumption

# Queue and Exchange for Chat
rabbitmq.exchange.chat=chat.exchange
rabbitmq.queue.chat=chat.events.queue
rabbitmq.routing.key.chat=chat.events.key

# Logging
logging.level.com.example.websocket=INFO
logging.level.org.springframework.web.socket=DEBUG
