server.port=${SERVER_PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/monitoring-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Queue names
rabbitmq.queue.device.data=device.data.queue
rabbitmq.queue.sync=synchronization.queue
rabbitmq.exchange.device.data=device.data.exchange
rabbitmq.exchange.sync=synchronization.exchange
rabbitmq.routing.key.device.data=device.data.routing.key
rabbitmq.routing.key.sync.user=sync.user
rabbitmq.routing.key.sync.device=sync.device

# Energy & Alerts
rabbitmq.exchange.energy=energy.hourly.exchange
rabbitmq.routing.key.energy=energy.hourly.key
rabbitmq.queue.energy=energy.hourly.queue
monitoring.overconsumption.threshold.kwh=${OVERCONSUMPTION_THRESHOLD:50}

# Logging
logging.level.com.example.monitoring=INFO
logging.level.org.springframework.amqp=DEBUG
